---
name: SDK-java

on:
  pull_request

jobs:
  gradle:
    name: Java sdk
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Ensure java exists ?
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: start gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.5

      - name: build sdk
        uses: gradle/gradle-build-action@v2
        with:
          arguments: clean build
          build-root-directory: .

